### ISSUE TITLE
About your knn radius

### ISSUE THREAD

**Issue by YunfanChen** [konosp/propensity-score-matching#1]
In your jupyter notebook, you use Nearerst Neighbors to identify matching candidates.

`caliper = np.std(df_data.propensity_score) * 0.25
knn = NearestNeighbors(n_neighbors=10 , p = 2, radius=caliper)`

In this line, why you choose caliper as radius? Thank you.

**Comment by YunfanChen** [comment]
In addition, for other dataset, is caliper still be **1/4** of standart deviation of logit(propensity score)？
Is **1/4**  a magic value?

**Comment by konosp** [comment]
Hey @YunfanChen, i used that based on online references I found (example: https://youtu.be/gaUgW7NWai8?t=997).
I did not experiment to adjust the value of the radius.

I suppose in various cases, different ranges would perform differently.

I hope the link above helps. Let me know

**Comment by YunfanChen** [comment]
> Hey @YunfanChen, i used that based on online references I found (example: https://youtu.be/gaUgW7NWai8?t=997).
> I did not experiment to adjust the value of the radius.
> 
> I suppose in various cases, different ranges would perform differently.
> 
> I hope the link above helps. Let me know

This reference is really helpful for me, thanks!
